databases:
  - name: smartcms_db
    databaseName: smartcms
    user: smartcms_user

services:
  - type: web
    name: smartcms
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate
    startCommand: gunicorn smartcms.wsgi:application
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: smartcms_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "*"
